# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatbufSignatureLibrary

import flatbuffers

class CallRef(object):
    __slots__ = ['_tab']

    # CallRef
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallRef
    def Offset(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # CallRef
    def DstId(self): return self._tab.Get(flatbuffers.number_types.Int32Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(4))

def CreateCallRef(builder, offset, dstId):
    builder.Prep(4, 8)
    builder.PrependInt32(dstId)
    builder.PrependInt32(offset)
    return builder.Offset()
