# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FlatbufSignatureLibrary

import flatbuffers

class SignatureLibrary(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsSignatureLibrary(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = SignatureLibrary()
        x.Init(buf, n + offset)
        return x

    # SignatureLibrary
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # SignatureLibrary
    def Functions(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from .Function import Function
            obj = Function()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # SignatureLibrary
    def FunctionsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # SignatureLibrary
    def Root(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from .TrieNode import TrieNode
            obj = TrieNode()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def SignatureLibraryStart(builder): builder.StartObject(2)
def SignatureLibraryAddFunctions(builder, functions): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(functions), 0)
def SignatureLibraryStartFunctionsVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def SignatureLibraryAddRoot(builder, root): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(root), 0)
def SignatureLibraryEnd(builder): return builder.EndObject()
